---
# This role installs all needed packages


- name: Update again
  apt: update_cache=yes

- name: Install all packages we need
  apt: name={{item}} state=present
  with_items:
    - htop
    - build-essential
    - git
    - vim

- name: Make sure locales are installed
  apt: name={{item}} state=present
  with_items:
    - language-pack-en
    - language-pack-en-base

- name: Configure locales
  locale_gen: name=en_US.UTF-8 state=present

- name: Set timezone to Europe/Amsterdam
  template: dest=/etc/timezone src=timezone.j2
  notify: update tzdata
